# Use stable version of official RabbitMQ image with management plugin
FROM rabbitmq:alpine

# Labels
LABEL maintainer="jouhar-dydx"
LABEL version="1.0"
LABEL description="merope RabbitMQ with externalized configs"

#ENV RABBITMQ_LOAD_DEFINITIONS=true
#ENV RABBITMQ_USE_LONGNAME=true
#ENV RABBITMQ_DEFINITION_FILE=/etc/rabbitmq/definitions.json

# Expose ports
EXPOSE 5672
EXPOSE 15672
